name: Node.js CI

on: [push]

jobs:
  coverage:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - name: Run unit tests
        run: |
        echo "DATAVERSE_KEY=$DATAVERSE_KEY" > .env
        npm test -- --coverage --collectCoverageFrom="./src/**"
        env:
            DATAVERSE_KEY: ${{ secrets.DATAVERSE_KEY }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
